config/routes.rb
Rails.application.routes.draw do

	root :to => "bets#index"

  	resources :bets
  	resources :rounds
  	resources :players
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :player
  belongs_to :round
end

app/models/player.rb
class Player < ApplicationRecord
	has_many :bets
end

app/models/round.rb
class Round < ApplicationRecord
	has_many :bets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy]

  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bet }
      else
        format.html { render :edit }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:amount, :player_id, :round_id)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    @player.money = 10000

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.jsonPablo
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :money)
    end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:number, :dateTime, :conservative, :result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/bets/_form.html.erb
<%= form_with(model: bet, local: true) do |form| %>
  <% if bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, id: :bet_amount %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.text_field :player_id, id: :bet_player_id %>
  </div>

  <div class="field">
    <%= form.label :round_id %>
    <%= form.text_field :round_id, id: :bet_round_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Juego de la Ruleta</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Player</th>
      <th>Round</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.amount %></td>
        <td><%= bet.player %></td>
        <td><%= bet.round %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_bet_path %>
<%= link_to 'New Player', new_player_path %>

app/views/bets/new.html.erb
<h1>New Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<h1> Ruleta </h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @bet.amount %>
</p>

<p>
  <strong>Player:</strong>
  <%= @bet.player %>
</p>

<p>
  <strong>Round:</strong>
  <%= @bet.round %>
</p>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RuletaRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :player_name %>
  </div>

  <div class="field">
    <%= form.label :money %>
    <%= form.number_field :money, id: :player_money %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.money %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= form_for :player, url: players_path do |f| %>
  <p>
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </p> 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Money:</strong>
  <%= @player.money %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/rounds/_form.html.erb
<%= form_with(model: round, local: true) do |form| %>
  <% if round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :round_number %>
  </div>

  <div class="field">
    <%= form.label :dateTime %>
    <%= form.datetime_select :dateTime, id: :round_dateTime %>
  </div>

  <div class="field">
    <%= form.label :conservative %>
    <%= form.check_box :conservative, id: :round_conservative %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.text_field :result, id: :round_result %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rounds</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Datetime</th>
      <th>Conservative</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.number %></td>
        <td><%= round.dateTime %></td>
        <td><%= round.conservative %></td>
        <td><%= round.result %></td>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<h1>New Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @round.number %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @round.dateTime %>
</p>

<p>
  <strong>Conservative:</strong>
  <%= @round.conservative %>
</p>

<p>
  <strong>Result:</strong>
  <%= @round.result %>
</p>

<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>